apiVersion: v2
name: vote
description: Voting frontend - Python Flask web app
type: application
version: 1.0.0
appVersion: "1.0"

keywords:
  - vote
  - frontend
  - flask
  - python

maintainers:
  - name: Luciana Cristaldo
